{
    "title":"title2",
    "logoImgPath":"logo1",
    "headline":"line1",
    "description":"d1",
    "appearanceDTO":{
        "fontName":"font1",
        "backgroundColor":"#ffffff",
        "backgroundImagePath":"",
        "pictureStretching":"FULL_SCREEN",
        "mainColor":"#ff0000",
        "secondColor":"#f000ff",
        "galleryType":"COLLAGE"
    },
    "photoDTOS":[
        {
            "imgPath":"path1"
        },
        {
            "imgPath":"path2"
        }
    ],
    "contactDTOS":[
        {
            "type":"SOCIAL_NETWORK",
            "content":"inst_link"
        }
    ],
    "addressDTOS":[
        {
            "address":"add1",
            "showOnMap":true
        },
        {
            "address":"add2",
            "showOnMap":false
        }
    ]
}