// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AdminService.proto

package com.tsemkalo.businesscards.generatedProtos;

public interface AddSupporterRequestProtoListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tsemkalo.businesscards.generated.AddSupporterRequestProtoList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.AddSupporterRequestProto requests = 1;</code>
   */
  java.util.List<AddSupporterRequestProto>
      getRequestsList();
  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.AddSupporterRequestProto requests = 1;</code>
   */
  AddSupporterRequestProto getRequests(int index);
  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.AddSupporterRequestProto requests = 1;</code>
   */
  int getRequestsCount();
  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.AddSupporterRequestProto requests = 1;</code>
   */
  java.util.List<? extends AddSupporterRequestProtoOrBuilder>
      getRequestsOrBuilderList();
  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.AddSupporterRequestProto requests = 1;</code>
   */
  AddSupporterRequestProtoOrBuilder getRequestsOrBuilder(
      int index);
}
