// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CardService.proto

package com.tsemkalo.businesscards.generatedProtos;

/**
 * Protobuf type {@code com.tsemkalo.businesscards.generated.AppearanceProto}
 */
public  final class AppearanceProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.tsemkalo.businesscards.generated.AppearanceProto)
    AppearanceProtoOrBuilder {
  // Use AppearanceProto.newBuilder() to construct.
  private AppearanceProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AppearanceProto() {
    id_ = 0L;
    cardId_ = 0L;
    fontName_ = "";
    backgroundColor_ = "";
    backgroundImagePath_ = "";
    pictureStretching_ = 0;
    mainColor_ = "";
    secondColor_ = "";
    galleryType_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private AppearanceProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 16: {

            cardId_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            fontName_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            backgroundColor_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            backgroundImagePath_ = s;
            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            pictureStretching_ = rawValue;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            mainColor_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            secondColor_ = s;
            break;
          }
          case 72: {
            int rawValue = input.readEnum();

            galleryType_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CardServiceOuterClass.internal_static_com_tsemkalo_businesscards_AppearanceProto_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CardServiceOuterClass.internal_static_com_tsemkalo_businesscards_AppearanceProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            AppearanceProto.class, AppearanceProto.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int CARDID_FIELD_NUMBER = 2;
  private long cardId_;
  /**
   * <code>int64 cardId = 2;</code>
   */
  public long getCardId() {
    return cardId_;
  }

  public static final int FONTNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object fontName_;
  /**
   * <code>string fontName = 3;</code>
   */
  public java.lang.String getFontName() {
    java.lang.Object ref = fontName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fontName_ = s;
      return s;
    }
  }
  /**
   * <code>string fontName = 3;</code>
   */
  public com.google.protobuf.ByteString
      getFontNameBytes() {
    java.lang.Object ref = fontName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fontName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BACKGROUNDCOLOR_FIELD_NUMBER = 4;
  private volatile java.lang.Object backgroundColor_;
  /**
   * <code>string backgroundColor = 4;</code>
   */
  public java.lang.String getBackgroundColor() {
    java.lang.Object ref = backgroundColor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      backgroundColor_ = s;
      return s;
    }
  }
  /**
   * <code>string backgroundColor = 4;</code>
   */
  public com.google.protobuf.ByteString
      getBackgroundColorBytes() {
    java.lang.Object ref = backgroundColor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      backgroundColor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BACKGROUNDIMAGEPATH_FIELD_NUMBER = 5;
  private volatile java.lang.Object backgroundImagePath_;
  /**
   * <code>string backgroundImagePath = 5;</code>
   */
  public java.lang.String getBackgroundImagePath() {
    java.lang.Object ref = backgroundImagePath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      backgroundImagePath_ = s;
      return s;
    }
  }
  /**
   * <code>string backgroundImagePath = 5;</code>
   */
  public com.google.protobuf.ByteString
      getBackgroundImagePathBytes() {
    java.lang.Object ref = backgroundImagePath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      backgroundImagePath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PICTURESTRETCHING_FIELD_NUMBER = 6;
  private int pictureStretching_;
  /**
   * <code>.com.tsemkalo.businesscards.generated.ProtoPictureStretchingType pictureStretching = 6;</code>
   */
  public int getPictureStretchingValue() {
    return pictureStretching_;
  }
  /**
   * <code>.com.tsemkalo.businesscards.generated.ProtoPictureStretchingType pictureStretching = 6;</code>
   */
  public ProtoPictureStretchingType getPictureStretching() {
    ProtoPictureStretchingType result = ProtoPictureStretchingType.valueOf(pictureStretching_);
    return result == null ? ProtoPictureStretchingType.UNRECOGNIZED : result;
  }

  public static final int MAINCOLOR_FIELD_NUMBER = 7;
  private volatile java.lang.Object mainColor_;
  /**
   * <code>string mainColor = 7;</code>
   */
  public java.lang.String getMainColor() {
    java.lang.Object ref = mainColor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mainColor_ = s;
      return s;
    }
  }
  /**
   * <code>string mainColor = 7;</code>
   */
  public com.google.protobuf.ByteString
      getMainColorBytes() {
    java.lang.Object ref = mainColor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mainColor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SECONDCOLOR_FIELD_NUMBER = 8;
  private volatile java.lang.Object secondColor_;
  /**
   * <code>string secondColor = 8;</code>
   */
  public java.lang.String getSecondColor() {
    java.lang.Object ref = secondColor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      secondColor_ = s;
      return s;
    }
  }
  /**
   * <code>string secondColor = 8;</code>
   */
  public com.google.protobuf.ByteString
      getSecondColorBytes() {
    java.lang.Object ref = secondColor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      secondColor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GALLERYTYPE_FIELD_NUMBER = 9;
  private int galleryType_;
  /**
   * <code>.com.tsemkalo.businesscards.generated.ProtoGalleryType galleryType = 9;</code>
   */
  public int getGalleryTypeValue() {
    return galleryType_;
  }
  /**
   * <code>.com.tsemkalo.businesscards.generated.ProtoGalleryType galleryType = 9;</code>
   */
  public ProtoGalleryType getGalleryType() {
    ProtoGalleryType result = ProtoGalleryType.valueOf(galleryType_);
    return result == null ? ProtoGalleryType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (cardId_ != 0L) {
      output.writeInt64(2, cardId_);
    }
    if (!getFontNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fontName_);
    }
    if (!getBackgroundColorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, backgroundColor_);
    }
    if (!getBackgroundImagePathBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, backgroundImagePath_);
    }
    if (pictureStretching_ != ProtoPictureStretchingType.FULL_SCREEN.getNumber()) {
      output.writeEnum(6, pictureStretching_);
    }
    if (!getMainColorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, mainColor_);
    }
    if (!getSecondColorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, secondColor_);
    }
    if (galleryType_ != ProtoGalleryType.COLLAGE.getNumber()) {
      output.writeEnum(9, galleryType_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (cardId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, cardId_);
    }
    if (!getFontNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, fontName_);
    }
    if (!getBackgroundColorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, backgroundColor_);
    }
    if (!getBackgroundImagePathBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, backgroundImagePath_);
    }
    if (pictureStretching_ != ProtoPictureStretchingType.FULL_SCREEN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, pictureStretching_);
    }
    if (!getMainColorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, mainColor_);
    }
    if (!getSecondColorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, secondColor_);
    }
    if (galleryType_ != ProtoGalleryType.COLLAGE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(9, galleryType_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof AppearanceProto)) {
      return super.equals(obj);
    }
    AppearanceProto other = (AppearanceProto) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && (getCardId()
        == other.getCardId());
    result = result && getFontName()
        .equals(other.getFontName());
    result = result && getBackgroundColor()
        .equals(other.getBackgroundColor());
    result = result && getBackgroundImagePath()
        .equals(other.getBackgroundImagePath());
    result = result && pictureStretching_ == other.pictureStretching_;
    result = result && getMainColor()
        .equals(other.getMainColor());
    result = result && getSecondColor()
        .equals(other.getSecondColor());
    result = result && galleryType_ == other.galleryType_;
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + CARDID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCardId());
    hash = (37 * hash) + FONTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getFontName().hashCode();
    hash = (37 * hash) + BACKGROUNDCOLOR_FIELD_NUMBER;
    hash = (53 * hash) + getBackgroundColor().hashCode();
    hash = (37 * hash) + BACKGROUNDIMAGEPATH_FIELD_NUMBER;
    hash = (53 * hash) + getBackgroundImagePath().hashCode();
    hash = (37 * hash) + PICTURESTRETCHING_FIELD_NUMBER;
    hash = (53 * hash) + pictureStretching_;
    hash = (37 * hash) + MAINCOLOR_FIELD_NUMBER;
    hash = (53 * hash) + getMainColor().hashCode();
    hash = (37 * hash) + SECONDCOLOR_FIELD_NUMBER;
    hash = (53 * hash) + getSecondColor().hashCode();
    hash = (37 * hash) + GALLERYTYPE_FIELD_NUMBER;
    hash = (53 * hash) + galleryType_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static AppearanceProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AppearanceProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AppearanceProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AppearanceProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AppearanceProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AppearanceProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AppearanceProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AppearanceProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static AppearanceProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static AppearanceProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static AppearanceProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AppearanceProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(AppearanceProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.tsemkalo.businesscards.generated.AppearanceProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.tsemkalo.businesscards.generated.AppearanceProto)
          AppearanceProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CardServiceOuterClass.internal_static_com_tsemkalo_businesscards_AppearanceProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CardServiceOuterClass.internal_static_com_tsemkalo_businesscards_AppearanceProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AppearanceProto.class, AppearanceProto.Builder.class);
    }

    // Construct using com.tsemkalo.businesscards.generated.AppearanceProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0L;

      cardId_ = 0L;

      fontName_ = "";

      backgroundColor_ = "";

      backgroundImagePath_ = "";

      pictureStretching_ = 0;

      mainColor_ = "";

      secondColor_ = "";

      galleryType_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CardServiceOuterClass.internal_static_com_tsemkalo_businesscards_AppearanceProto_descriptor;
    }

    public AppearanceProto getDefaultInstanceForType() {
      return AppearanceProto.getDefaultInstance();
    }

    public AppearanceProto build() {
      AppearanceProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public AppearanceProto buildPartial() {
      AppearanceProto result = new AppearanceProto(this);
      result.id_ = id_;
      result.cardId_ = cardId_;
      result.fontName_ = fontName_;
      result.backgroundColor_ = backgroundColor_;
      result.backgroundImagePath_ = backgroundImagePath_;
      result.pictureStretching_ = pictureStretching_;
      result.mainColor_ = mainColor_;
      result.secondColor_ = secondColor_;
      result.galleryType_ = galleryType_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof AppearanceProto) {
        return mergeFrom((AppearanceProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(AppearanceProto other) {
      if (other == AppearanceProto.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.getCardId() != 0L) {
        setCardId(other.getCardId());
      }
      if (!other.getFontName().isEmpty()) {
        fontName_ = other.fontName_;
        onChanged();
      }
      if (!other.getBackgroundColor().isEmpty()) {
        backgroundColor_ = other.backgroundColor_;
        onChanged();
      }
      if (!other.getBackgroundImagePath().isEmpty()) {
        backgroundImagePath_ = other.backgroundImagePath_;
        onChanged();
      }
      if (other.pictureStretching_ != 0) {
        setPictureStretchingValue(other.getPictureStretchingValue());
      }
      if (!other.getMainColor().isEmpty()) {
        mainColor_ = other.mainColor_;
        onChanged();
      }
      if (!other.getSecondColor().isEmpty()) {
        secondColor_ = other.secondColor_;
        onChanged();
      }
      if (other.galleryType_ != 0) {
        setGalleryTypeValue(other.getGalleryTypeValue());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      AppearanceProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (AppearanceProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private long cardId_ ;
    /**
     * <code>int64 cardId = 2;</code>
     */
    public long getCardId() {
      return cardId_;
    }
    /**
     * <code>int64 cardId = 2;</code>
     */
    public Builder setCardId(long value) {
      
      cardId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 cardId = 2;</code>
     */
    public Builder clearCardId() {
      
      cardId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object fontName_ = "";
    /**
     * <code>string fontName = 3;</code>
     */
    public java.lang.String getFontName() {
      java.lang.Object ref = fontName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fontName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fontName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFontNameBytes() {
      java.lang.Object ref = fontName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fontName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fontName = 3;</code>
     */
    public Builder setFontName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fontName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string fontName = 3;</code>
     */
    public Builder clearFontName() {
      
      fontName_ = getDefaultInstance().getFontName();
      onChanged();
      return this;
    }
    /**
     * <code>string fontName = 3;</code>
     */
    public Builder setFontNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fontName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object backgroundColor_ = "";
    /**
     * <code>string backgroundColor = 4;</code>
     */
    public java.lang.String getBackgroundColor() {
      java.lang.Object ref = backgroundColor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        backgroundColor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string backgroundColor = 4;</code>
     */
    public com.google.protobuf.ByteString
        getBackgroundColorBytes() {
      java.lang.Object ref = backgroundColor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        backgroundColor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string backgroundColor = 4;</code>
     */
    public Builder setBackgroundColor(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      backgroundColor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string backgroundColor = 4;</code>
     */
    public Builder clearBackgroundColor() {
      
      backgroundColor_ = getDefaultInstance().getBackgroundColor();
      onChanged();
      return this;
    }
    /**
     * <code>string backgroundColor = 4;</code>
     */
    public Builder setBackgroundColorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      backgroundColor_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object backgroundImagePath_ = "";
    /**
     * <code>string backgroundImagePath = 5;</code>
     */
    public java.lang.String getBackgroundImagePath() {
      java.lang.Object ref = backgroundImagePath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        backgroundImagePath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string backgroundImagePath = 5;</code>
     */
    public com.google.protobuf.ByteString
        getBackgroundImagePathBytes() {
      java.lang.Object ref = backgroundImagePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        backgroundImagePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string backgroundImagePath = 5;</code>
     */
    public Builder setBackgroundImagePath(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      backgroundImagePath_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string backgroundImagePath = 5;</code>
     */
    public Builder clearBackgroundImagePath() {
      
      backgroundImagePath_ = getDefaultInstance().getBackgroundImagePath();
      onChanged();
      return this;
    }
    /**
     * <code>string backgroundImagePath = 5;</code>
     */
    public Builder setBackgroundImagePathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      backgroundImagePath_ = value;
      onChanged();
      return this;
    }

    private int pictureStretching_ = 0;
    /**
     * <code>.com.tsemkalo.businesscards.generated.ProtoPictureStretchingType pictureStretching = 6;</code>
     */
    public int getPictureStretchingValue() {
      return pictureStretching_;
    }
    /**
     * <code>.com.tsemkalo.businesscards.generated.ProtoPictureStretchingType pictureStretching = 6;</code>
     */
    public Builder setPictureStretchingValue(int value) {
      pictureStretching_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.tsemkalo.businesscards.generated.ProtoPictureStretchingType pictureStretching = 6;</code>
     */
    public ProtoPictureStretchingType getPictureStretching() {
      ProtoPictureStretchingType result = ProtoPictureStretchingType.valueOf(pictureStretching_);
      return result == null ? ProtoPictureStretchingType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.tsemkalo.businesscards.generated.ProtoPictureStretchingType pictureStretching = 6;</code>
     */
    public Builder setPictureStretching(ProtoPictureStretchingType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      pictureStretching_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.tsemkalo.businesscards.generated.ProtoPictureStretchingType pictureStretching = 6;</code>
     */
    public Builder clearPictureStretching() {
      
      pictureStretching_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object mainColor_ = "";
    /**
     * <code>string mainColor = 7;</code>
     */
    public java.lang.String getMainColor() {
      java.lang.Object ref = mainColor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mainColor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mainColor = 7;</code>
     */
    public com.google.protobuf.ByteString
        getMainColorBytes() {
      java.lang.Object ref = mainColor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mainColor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mainColor = 7;</code>
     */
    public Builder setMainColor(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mainColor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string mainColor = 7;</code>
     */
    public Builder clearMainColor() {
      
      mainColor_ = getDefaultInstance().getMainColor();
      onChanged();
      return this;
    }
    /**
     * <code>string mainColor = 7;</code>
     */
    public Builder setMainColorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mainColor_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object secondColor_ = "";
    /**
     * <code>string secondColor = 8;</code>
     */
    public java.lang.String getSecondColor() {
      java.lang.Object ref = secondColor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        secondColor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string secondColor = 8;</code>
     */
    public com.google.protobuf.ByteString
        getSecondColorBytes() {
      java.lang.Object ref = secondColor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        secondColor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string secondColor = 8;</code>
     */
    public Builder setSecondColor(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      secondColor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string secondColor = 8;</code>
     */
    public Builder clearSecondColor() {
      
      secondColor_ = getDefaultInstance().getSecondColor();
      onChanged();
      return this;
    }
    /**
     * <code>string secondColor = 8;</code>
     */
    public Builder setSecondColorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      secondColor_ = value;
      onChanged();
      return this;
    }

    private int galleryType_ = 0;
    /**
     * <code>.com.tsemkalo.businesscards.generated.ProtoGalleryType galleryType = 9;</code>
     */
    public int getGalleryTypeValue() {
      return galleryType_;
    }
    /**
     * <code>.com.tsemkalo.businesscards.generated.ProtoGalleryType galleryType = 9;</code>
     */
    public Builder setGalleryTypeValue(int value) {
      galleryType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.tsemkalo.businesscards.generated.ProtoGalleryType galleryType = 9;</code>
     */
    public ProtoGalleryType getGalleryType() {
      ProtoGalleryType result = ProtoGalleryType.valueOf(galleryType_);
      return result == null ? ProtoGalleryType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.tsemkalo.businesscards.generated.ProtoGalleryType galleryType = 9;</code>
     */
    public Builder setGalleryType(ProtoGalleryType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      galleryType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.tsemkalo.businesscards.generated.ProtoGalleryType galleryType = 9;</code>
     */
    public Builder clearGalleryType() {
      
      galleryType_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.tsemkalo.businesscards.generated.AppearanceProto)
  }

  // @@protoc_insertion_point(class_scope:com.tsemkalo.businesscards.generated.AppearanceProto)
  private static final AppearanceProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new AppearanceProto();
  }

  public static AppearanceProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AppearanceProto>
      PARSER = new com.google.protobuf.AbstractParser<AppearanceProto>() {
    public AppearanceProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new AppearanceProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AppearanceProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AppearanceProto> getParserForType() {
    return PARSER;
  }

  public AppearanceProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

