// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CardService.proto

package com.tsemkalo.businesscards.generatedProtos;

public final class CardServiceOuterClass {
  private CardServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tsemkalo_businesscards_CardListProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tsemkalo_businesscards_CardListProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tsemkalo_businesscards_CardProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tsemkalo_businesscards_CardProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tsemkalo_businesscards_AddressProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tsemkalo_businesscards_AddressProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tsemkalo_businesscards_ContactProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tsemkalo_businesscards_ContactProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tsemkalo_businesscards_GalleryPhotoProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tsemkalo_businesscards_GalleryPhotoProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tsemkalo_businesscards_FollowProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tsemkalo_businesscards_FollowProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tsemkalo_businesscards_LikeProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tsemkalo_businesscards_LikeProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tsemkalo_businesscards_IdValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tsemkalo_businesscards_IdValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tsemkalo_businesscards_AppearanceProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tsemkalo_businesscards_AppearanceProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tsemkalo_businesscards_EditCardProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tsemkalo_businesscards_EditCardProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tsemkalo_businesscards_DeleteCardProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tsemkalo_businesscards_DeleteCardProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tsemkalo_businesscards_EditAddressProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tsemkalo_businesscards_EditAddressProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tsemkalo_businesscards_DeleteAddressProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tsemkalo_businesscards_DeleteAddressProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tsemkalo_businesscards_EditContactProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tsemkalo_businesscards_EditContactProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tsemkalo_businesscards_DeleteContactProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tsemkalo_businesscards_DeleteContactProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tsemkalo_businesscards_EditAppearanceProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tsemkalo_businesscards_EditAppearanceProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tsemkalo_businesscards_EditGalleryPhotoProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tsemkalo_businesscards_EditGalleryPhotoProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tsemkalo_businesscards_DeleteGalleryPhotoProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tsemkalo_businesscards_DeleteGalleryPhotoProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021CardService.proto\022\032com.tsemkalo.busine" +
      "sscards\032\033google/protobuf/empty.proto\"E\n\r" +
      "CardListProto\0224\n\005cards\030\001 \003(\0132%.com.tsemk" +
      "alo.businesscards.CardProto\"\231\003\n\tCardProt" +
      "o\022\n\n\002id\030\001 \001(\003\022\016\n\006userId\030\002 \001(\003\022\r\n\005title\030\003" +
      " \001(\t\022\023\n\013logoImgPath\030\004 \001(\t\022\020\n\010headline\030\005 " +
      "\001(\t\022\023\n\013description\030\006 \001(\t\022=\n\006photos\030\007 \003(\013" +
      "2-.com.tsemkalo.businesscards.GalleryPho" +
      "toProto\022:\n\010contacts\030\010 \003(\0132(.com.tsemkalo" +
      ".businesscards.ContactProto\022;\n\taddresses",
      "\030\t \003(\0132(.com.tsemkalo.businesscards.Addr" +
      "essProto\022\027\n\017followersAmount\030\n \001(\005\022\023\n\013lik" +
      "esAmount\030\013 \001(\005\022?\n\nappearance\030\014 \001(\0132+.com" +
      ".tsemkalo.businesscards.AppearanceProto\"" +
      "N\n\014AddressProto\022\n\n\002id\030\001 \001(\003\022\017\n\007address\030\002" +
      " \001(\t\022\021\n\tshowOnMap\030\003 \001(\010\022\016\n\006cardId\030\004 \001(\003\"" +
      "w\n\014ContactProto\022\n\n\002id\030\001 \001(\003\022:\n\004type\030\002 \001(" +
      "\0162,.com.tsemkalo.businesscards.ProtoCont" +
      "actType\022\017\n\007content\030\003 \001(\t\022\016\n\006cardId\030\004 \001(\003" +
      "\"@\n\021GalleryPhotoProto\022\n\n\002id\030\001 \001(\003\022\016\n\006car",
      "dId\030\002 \001(\003\022\017\n\007imgPath\030\003 \001(\t\"9\n\013FollowProt" +
      "o\022\n\n\002id\030\001 \001(\003\022\016\n\006userId\030\002 \001(\003\022\016\n\006cardId\030" +
      "\003 \001(\003\"7\n\tLikeProto\022\n\n\002id\030\001 \001(\003\022\016\n\006userId" +
      "\030\002 \001(\003\022\016\n\006cardId\030\003 \001(\003\"\025\n\007IdValue\022\n\n\002id\030" +
      "\001 \001(\003\"\263\002\n\017AppearanceProto\022\n\n\002id\030\001 \001(\003\022\016\n" +
      "\006cardId\030\002 \001(\003\022\020\n\010fontName\030\003 \001(\t\022\027\n\017backg" +
      "roundColor\030\004 \001(\t\022\033\n\023backgroundImagePath\030" +
      "\005 \001(\t\022Q\n\021pictureStretching\030\006 \001(\01626.com.t" +
      "semkalo.businesscards.ProtoPictureStretc" +
      "hingType\022\021\n\tmainColor\030\007 \001(\t\022\023\n\013secondCol",
      "or\030\010 \001(\t\022A\n\013galleryType\030\t \001(\0162,.com.tsem" +
      "kalo.businesscards.ProtoGalleryType\"o\n\rE" +
      "ditCardProto\0228\n\tcardProto\030\001 \001(\0132%.com.ts" +
      "emkalo.businesscards.CardProto\022\025\n\rcurren" +
      "tUserId\030\002 \001(\003\022\r\n\005admin\030\003 \001(\010\"G\n\017DeleteCa" +
      "rdProto\022\016\n\006cardId\030\001 \001(\003\022\025\n\rcurrentUserId" +
      "\030\002 \001(\003\022\r\n\005admin\030\003 \001(\010\"\210\001\n\020EditAddressPro" +
      "to\022>\n\014addressProto\030\001 \001(\0132(.com.tsemkalo." +
      "businesscards.AddressProto\022\025\n\rcurrentUse" +
      "rId\030\002 \001(\003\022\r\n\005admin\030\003 \001(\010\022\016\n\006cardId\030\004 \001(\003",
      "\"]\n\022DeleteAddressProto\022\021\n\taddressId\030\001 \001(" +
      "\003\022\025\n\rcurrentUserId\030\002 \001(\003\022\r\n\005admin\030\003 \001(\010\022" +
      "\016\n\006cardId\030\004 \001(\003\"\210\001\n\020EditContactProto\022>\n\014" +
      "contactProto\030\001 \001(\0132(.com.tsemkalo.busine" +
      "sscards.ContactProto\022\025\n\rcurrentUserId\030\002 " +
      "\001(\003\022\r\n\005admin\030\003 \001(\010\022\016\n\006cardId\030\004 \001(\003\"]\n\022De" +
      "leteContactProto\022\021\n\tcontactId\030\001 \001(\003\022\025\n\rc" +
      "urrentUserId\030\002 \001(\003\022\r\n\005admin\030\003 \001(\010\022\016\n\006car" +
      "dId\030\004 \001(\003\"\221\001\n\023EditAppearanceProto\022D\n\017app" +
      "earanceProto\030\001 \001(\0132+.com.tsemkalo.busine",
      "sscards.AppearanceProto\022\025\n\rcurrentUserId" +
      "\030\002 \001(\003\022\r\n\005admin\030\003 \001(\010\022\016\n\006cardId\030\004 \001(\003\"\227\001" +
      "\n\025EditGalleryPhotoProto\022H\n\021galleryPhotoP" +
      "roto\030\001 \001(\0132-.com.tsemkalo.businesscards." +
      "GalleryPhotoProto\022\025\n\rcurrentUserId\030\002 \001(\003" +
      "\022\r\n\005admin\030\003 \001(\010\022\016\n\006cardId\030\004 \001(\003\"g\n\027Delet" +
      "eGalleryPhotoProto\022\026\n\016galleryPhotoId\030\001 \001" +
      "(\003\022\025\n\rcurrentUserId\030\002 \001(\003\022\r\n\005admin\030\003 \001(\010" +
      "\022\016\n\006cardId\030\004 \001(\003*X\n\020ProtoContactType\022\022\n\016" +
      "SOCIAL_NETWORK\020\000\022\020\n\014PHONE_NUMBER\020\001\022\020\n\014MA",
      "IL_ADDRESS\020\002\022\014\n\010WEB_SITE\020\003*\263\001\n\032ProtoPict" +
      "ureStretchingType\022\017\n\013FULL_SCREEN\020\000\022\021\n\rFU" +
      "LL_DOCUMENT\020\001\022\"\n\036WIDTH_STRETCH_REPEAT_BY" +
      "_HEIGHT\020\002\022\031\n\025FULL_DOCUMENT_STRETCH\020\003\022\021\n\r" +
      "SCREEN_CENTER\020\004\022\023\n\017DOCUMENT_CENTER\020\005\022\n\n\006" +
      "REPEAT\020\006*7\n\020ProtoGalleryType\022\013\n\007COLLAGE\020" +
      "\000\022\010\n\004GRID\020\001\022\014\n\010CAROUSEL\020\0022\354\r\n\013CardServic" +
      "e\022Y\n\007addCard\022).com.tsemkalo.businesscard" +
      "s.EditCardProto\032#.com.tsemkalo.businessc" +
      "ards.IdValue\022M\n\010editCard\022).com.tsemkalo.",
      "businesscards.EditCardProto\032\026.google.pro" +
      "tobuf.Empty\022Q\n\ndeleteCard\022+.com.tsemkalo" +
      ".businesscards.DeleteCardProto\032\026.google." +
      "protobuf.Empty\022]\n\017getCardInfoById\022#.com." +
      "tsemkalo.businesscards.IdValue\032%.com.tse" +
      "mkalo.businesscards.CardProto\022g\n\025getAllC" +
      "ardsInfoByUser\022#.com.tsemkalo.businessca" +
      "rds.IdValue\032).com.tsemkalo.businesscards" +
      ".CardListProto\022R\n\naddAddress\022,.com.tsemk" +
      "alo.businesscards.EditAddressProto\032\026.goo",
      "gle.protobuf.Empty\022W\n\rdeleteAddress\022..co" +
      "m.tsemkalo.businesscards.DeleteAddressPr" +
      "oto\032\026.google.protobuf.Empty\022S\n\013editAddre" +
      "ss\022,.com.tsemkalo.businesscards.EditAddr" +
      "essProto\032\026.google.protobuf.Empty\022R\n\naddC" +
      "ontact\022,.com.tsemkalo.businesscards.Edit" +
      "ContactProto\032\026.google.protobuf.Empty\022W\n\r" +
      "deleteContact\022..com.tsemkalo.businesscar" +
      "ds.DeleteContactProto\032\026.google.protobuf." +
      "Empty\022S\n\013editContact\022,.com.tsemkalo.busi",
      "nesscards.EditContactProto\032\026.google.prot" +
      "obuf.Empty\022\\\n\017addGalleryPhoto\0221.com.tsem" +
      "kalo.businesscards.EditGalleryPhotoProto" +
      "\032\026.google.protobuf.Empty\022]\n\020editGalleryP" +
      "hoto\0221.com.tsemkalo.businesscards.EditGa" +
      "lleryPhotoProto\032\026.google.protobuf.Empty\022" +
      "a\n\022deleteGalleryPhoto\0223.com.tsemkalo.bus" +
      "inesscards.DeleteGalleryPhotoProto\032\026.goo" +
      "gle.protobuf.Empty\022L\n\taddFollow\022\'.com.ts" +
      "emkalo.businesscards.FollowProto\032\026.googl",
      "e.protobuf.Empty\022O\n\014deleteFollow\022\'.com.t" +
      "semkalo.businesscards.FollowProto\032\026.goog" +
      "le.protobuf.Empty\022H\n\007addLike\022%.com.tsemk" +
      "alo.businesscards.LikeProto\032\026.google.pro" +
      "tobuf.Empty\022K\n\ndeleteLike\022%.com.tsemkalo" +
      ".businesscards.LikeProto\032\026.google.protob" +
      "uf.Empty\022Y\n\016editAppearance\022/.com.tsemkal" +
      "o.businesscards.EditAppearanceProto\032\026.go" +
      "ogle.protobuf.Empty\022c\n\021getUserFollowings" +
      "\022#.com.tsemkalo.businesscards.generated.IdValue\032).",
      "com.tsemkalo.businesscards.generated.CardListProto" +
      "B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_com_tsemkalo_businesscards_CardListProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_tsemkalo_businesscards_CardListProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tsemkalo_businesscards_CardListProto_descriptor,
        new java.lang.String[] { "Cards", });
    internal_static_com_tsemkalo_businesscards_CardProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_tsemkalo_businesscards_CardProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tsemkalo_businesscards_CardProto_descriptor,
        new java.lang.String[] { "Id", "UserId", "Title", "LogoImgPath", "Headline", "Description", "Photos", "Contacts", "Addresses", "FollowersAmount", "LikesAmount", "Appearance", });
    internal_static_com_tsemkalo_businesscards_AddressProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_tsemkalo_businesscards_AddressProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tsemkalo_businesscards_AddressProto_descriptor,
        new java.lang.String[] { "Id", "Address", "ShowOnMap", "CardId", });
    internal_static_com_tsemkalo_businesscards_ContactProto_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_tsemkalo_businesscards_ContactProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tsemkalo_businesscards_ContactProto_descriptor,
        new java.lang.String[] { "Id", "Type", "Content", "CardId", });
    internal_static_com_tsemkalo_businesscards_GalleryPhotoProto_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_tsemkalo_businesscards_GalleryPhotoProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tsemkalo_businesscards_GalleryPhotoProto_descriptor,
        new java.lang.String[] { "Id", "CardId", "ImgPath", });
    internal_static_com_tsemkalo_businesscards_FollowProto_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_tsemkalo_businesscards_FollowProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tsemkalo_businesscards_FollowProto_descriptor,
        new java.lang.String[] { "Id", "UserId", "CardId", });
    internal_static_com_tsemkalo_businesscards_LikeProto_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_tsemkalo_businesscards_LikeProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tsemkalo_businesscards_LikeProto_descriptor,
        new java.lang.String[] { "Id", "UserId", "CardId", });
    internal_static_com_tsemkalo_businesscards_IdValue_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_tsemkalo_businesscards_IdValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tsemkalo_businesscards_IdValue_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_tsemkalo_businesscards_AppearanceProto_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_tsemkalo_businesscards_AppearanceProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tsemkalo_businesscards_AppearanceProto_descriptor,
        new java.lang.String[] { "Id", "CardId", "FontName", "BackgroundColor", "BackgroundImagePath", "PictureStretching", "MainColor", "SecondColor", "GalleryType", });
    internal_static_com_tsemkalo_businesscards_EditCardProto_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_tsemkalo_businesscards_EditCardProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tsemkalo_businesscards_EditCardProto_descriptor,
        new java.lang.String[] { "CardProto", "CurrentUserId", "Admin", });
    internal_static_com_tsemkalo_businesscards_DeleteCardProto_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_tsemkalo_businesscards_DeleteCardProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tsemkalo_businesscards_DeleteCardProto_descriptor,
        new java.lang.String[] { "CardId", "CurrentUserId", "Admin", });
    internal_static_com_tsemkalo_businesscards_EditAddressProto_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_tsemkalo_businesscards_EditAddressProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tsemkalo_businesscards_EditAddressProto_descriptor,
        new java.lang.String[] { "AddressProto", "CurrentUserId", "Admin", "CardId", });
    internal_static_com_tsemkalo_businesscards_DeleteAddressProto_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_tsemkalo_businesscards_DeleteAddressProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tsemkalo_businesscards_DeleteAddressProto_descriptor,
        new java.lang.String[] { "AddressId", "CurrentUserId", "Admin", "CardId", });
    internal_static_com_tsemkalo_businesscards_EditContactProto_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_tsemkalo_businesscards_EditContactProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tsemkalo_businesscards_EditContactProto_descriptor,
        new java.lang.String[] { "ContactProto", "CurrentUserId", "Admin", "CardId", });
    internal_static_com_tsemkalo_businesscards_DeleteContactProto_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_tsemkalo_businesscards_DeleteContactProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tsemkalo_businesscards_DeleteContactProto_descriptor,
        new java.lang.String[] { "ContactId", "CurrentUserId", "Admin", "CardId", });
    internal_static_com_tsemkalo_businesscards_EditAppearanceProto_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_com_tsemkalo_businesscards_EditAppearanceProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tsemkalo_businesscards_EditAppearanceProto_descriptor,
        new java.lang.String[] { "AppearanceProto", "CurrentUserId", "Admin", "CardId", });
    internal_static_com_tsemkalo_businesscards_EditGalleryPhotoProto_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_com_tsemkalo_businesscards_EditGalleryPhotoProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tsemkalo_businesscards_EditGalleryPhotoProto_descriptor,
        new java.lang.String[] { "GalleryPhotoProto", "CurrentUserId", "Admin", "CardId", });
    internal_static_com_tsemkalo_businesscards_DeleteGalleryPhotoProto_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_com_tsemkalo_businesscards_DeleteGalleryPhotoProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tsemkalo_businesscards_DeleteGalleryPhotoProto_descriptor,
        new java.lang.String[] { "GalleryPhotoId", "CurrentUserId", "Admin", "CardId", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
