// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CardService.proto

package com.tsemkalo.businesscards.generatedProtos;

public interface CardListProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tsemkalo.businesscards.generated.CardListProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.CardProto cards = 1;</code>
   */
  java.util.List<CardProto>
      getCardsList();
  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.CardProto cards = 1;</code>
   */
  CardProto getCards(int index);
  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.CardProto cards = 1;</code>
   */
  int getCardsCount();
  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.CardProto cards = 1;</code>
   */
  java.util.List<? extends CardProtoOrBuilder>
      getCardsOrBuilderList();
  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.CardProto cards = 1;</code>
   */
  CardProtoOrBuilder getCardsOrBuilder(
      int index);
}
