// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.tsemkalo.businesscards.generatedProtos;

public interface ChangePasswordResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tsemkalo.businesscards.generated.ChangePasswordResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string newPassword = 1;</code>
   */
  java.lang.String getNewPassword();
  /**
   * <code>string newPassword = 1;</code>
   */
  com.google.protobuf.ByteString
      getNewPasswordBytes();
}
