// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageService.proto

package com.tsemkalo.businesscards.generatedProtos;

public interface ChatMemberProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tsemkalo.businesscards.generated.ChatMemberProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>int64 userId = 2;</code>
   */
  long getUserId();

  /**
   * <code>int64 chatId = 3;</code>
   */
  long getChatId();

  /**
   * <code>string memberName = 4;</code>
   */
  java.lang.String getMemberName();
  /**
   * <code>string memberName = 4;</code>
   */
  com.google.protobuf.ByteString
      getMemberNameBytes();

  /**
   * <code>bool notify = 5;</code>
   */
  boolean getNotify();
}
