// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageService.proto

package com.tsemkalo.businesscards.generatedProtos;

public interface ChatUserProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tsemkalo.businesscards.generated.ChatUserProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 chatId = 1;</code>
   */
  long getChatId();

  /**
   * <code>int64 userId = 2;</code>
   */
  long getUserId();
}
