// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageService.proto

package com.tsemkalo.businesscards.generatedProtos;

public interface ChatUserIdListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tsemkalo.businesscards.generated.ChatUserIdList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 userId = 1;</code>
   */
  java.util.List<java.lang.Long> getUserIdList();
  /**
   * <code>repeated int64 userId = 1;</code>
   */
  int getUserIdCount();
  /**
   * <code>repeated int64 userId = 1;</code>
   */
  long getUserId(int index);
}
