// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageService.proto

package com.tsemkalo.businesscards.generatedProtos;

/**
 * Protobuf type {@code com.tsemkalo.businesscards.generated.ChatProtoList}
 */
public  final class ChatProtoList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.tsemkalo.businesscards.generated.ChatProtoList)
    ChatProtoListOrBuilder {
  // Use ChatProtoList.newBuilder() to construct.
  private ChatProtoList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChatProtoList() {
    chat_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ChatProtoList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              chat_ = new java.util.ArrayList<ChatProto>();
              mutable_bitField0_ |= 0x00000001;
            }
            chat_.add(
                input.readMessage(ChatProto.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        chat_ = java.util.Collections.unmodifiableList(chat_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MessageServiceOuterClass.internal_static_com_tsemkalo_businesscards_ChatProtoList_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MessageServiceOuterClass.internal_static_com_tsemkalo_businesscards_ChatProtoList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ChatProtoList.class, ChatProtoList.Builder.class);
  }

  public static final int CHAT_FIELD_NUMBER = 1;
  private java.util.List<ChatProto> chat_;
  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.ChatProto chat = 1;</code>
   */
  public java.util.List<ChatProto> getChatList() {
    return chat_;
  }
  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.ChatProto chat = 1;</code>
   */
  public java.util.List<? extends ChatProtoOrBuilder>
      getChatOrBuilderList() {
    return chat_;
  }
  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.ChatProto chat = 1;</code>
   */
  public int getChatCount() {
    return chat_.size();
  }
  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.ChatProto chat = 1;</code>
   */
  public ChatProto getChat(int index) {
    return chat_.get(index);
  }
  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.ChatProto chat = 1;</code>
   */
  public ChatProtoOrBuilder getChatOrBuilder(
      int index) {
    return chat_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < chat_.size(); i++) {
      output.writeMessage(1, chat_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < chat_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, chat_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ChatProtoList)) {
      return super.equals(obj);
    }
    ChatProtoList other = (ChatProtoList) obj;

    boolean result = true;
    result = result && getChatList()
        .equals(other.getChatList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getChatCount() > 0) {
      hash = (37 * hash) + CHAT_FIELD_NUMBER;
      hash = (53 * hash) + getChatList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ChatProtoList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ChatProtoList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ChatProtoList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ChatProtoList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ChatProtoList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ChatProtoList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ChatProtoList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ChatProtoList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ChatProtoList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ChatProtoList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ChatProtoList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ChatProtoList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ChatProtoList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.tsemkalo.businesscards.generated.ChatProtoList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.tsemkalo.businesscards.generated.ChatProtoList)
          ChatProtoListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageServiceOuterClass.internal_static_com_tsemkalo_businesscards_ChatProtoList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageServiceOuterClass.internal_static_com_tsemkalo_businesscards_ChatProtoList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ChatProtoList.class, ChatProtoList.Builder.class);
    }

    // Construct using com.tsemkalo.businesscards.generated.ChatProtoList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getChatFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (chatBuilder_ == null) {
        chat_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        chatBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MessageServiceOuterClass.internal_static_com_tsemkalo_businesscards_ChatProtoList_descriptor;
    }

    public ChatProtoList getDefaultInstanceForType() {
      return ChatProtoList.getDefaultInstance();
    }

    public ChatProtoList build() {
      ChatProtoList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ChatProtoList buildPartial() {
      ChatProtoList result = new ChatProtoList(this);
      int from_bitField0_ = bitField0_;
      if (chatBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          chat_ = java.util.Collections.unmodifiableList(chat_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.chat_ = chat_;
      } else {
        result.chat_ = chatBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ChatProtoList) {
        return mergeFrom((ChatProtoList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ChatProtoList other) {
      if (other == ChatProtoList.getDefaultInstance()) return this;
      if (chatBuilder_ == null) {
        if (!other.chat_.isEmpty()) {
          if (chat_.isEmpty()) {
            chat_ = other.chat_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureChatIsMutable();
            chat_.addAll(other.chat_);
          }
          onChanged();
        }
      } else {
        if (!other.chat_.isEmpty()) {
          if (chatBuilder_.isEmpty()) {
            chatBuilder_.dispose();
            chatBuilder_ = null;
            chat_ = other.chat_;
            bitField0_ = (bitField0_ & ~0x00000001);
            chatBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getChatFieldBuilder() : null;
          } else {
            chatBuilder_.addAllMessages(other.chat_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ChatProtoList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ChatProtoList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<ChatProto> chat_ =
      java.util.Collections.emptyList();
    private void ensureChatIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        chat_ = new java.util.ArrayList<ChatProto>(chat_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            ChatProto, ChatProto.Builder, ChatProtoOrBuilder> chatBuilder_;

    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ChatProto chat = 1;</code>
     */
    public java.util.List<ChatProto> getChatList() {
      if (chatBuilder_ == null) {
        return java.util.Collections.unmodifiableList(chat_);
      } else {
        return chatBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ChatProto chat = 1;</code>
     */
    public int getChatCount() {
      if (chatBuilder_ == null) {
        return chat_.size();
      } else {
        return chatBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ChatProto chat = 1;</code>
     */
    public ChatProto getChat(int index) {
      if (chatBuilder_ == null) {
        return chat_.get(index);
      } else {
        return chatBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ChatProto chat = 1;</code>
     */
    public Builder setChat(
        int index, ChatProto value) {
      if (chatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChatIsMutable();
        chat_.set(index, value);
        onChanged();
      } else {
        chatBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ChatProto chat = 1;</code>
     */
    public Builder setChat(
        int index, ChatProto.Builder builderForValue) {
      if (chatBuilder_ == null) {
        ensureChatIsMutable();
        chat_.set(index, builderForValue.build());
        onChanged();
      } else {
        chatBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ChatProto chat = 1;</code>
     */
    public Builder addChat(ChatProto value) {
      if (chatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChatIsMutable();
        chat_.add(value);
        onChanged();
      } else {
        chatBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ChatProto chat = 1;</code>
     */
    public Builder addChat(
        int index, ChatProto value) {
      if (chatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChatIsMutable();
        chat_.add(index, value);
        onChanged();
      } else {
        chatBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ChatProto chat = 1;</code>
     */
    public Builder addChat(
        ChatProto.Builder builderForValue) {
      if (chatBuilder_ == null) {
        ensureChatIsMutable();
        chat_.add(builderForValue.build());
        onChanged();
      } else {
        chatBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ChatProto chat = 1;</code>
     */
    public Builder addChat(
        int index, ChatProto.Builder builderForValue) {
      if (chatBuilder_ == null) {
        ensureChatIsMutable();
        chat_.add(index, builderForValue.build());
        onChanged();
      } else {
        chatBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ChatProto chat = 1;</code>
     */
    public Builder addAllChat(
        java.lang.Iterable<? extends ChatProto> values) {
      if (chatBuilder_ == null) {
        ensureChatIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, chat_);
        onChanged();
      } else {
        chatBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ChatProto chat = 1;</code>
     */
    public Builder clearChat() {
      if (chatBuilder_ == null) {
        chat_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        chatBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ChatProto chat = 1;</code>
     */
    public Builder removeChat(int index) {
      if (chatBuilder_ == null) {
        ensureChatIsMutable();
        chat_.remove(index);
        onChanged();
      } else {
        chatBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ChatProto chat = 1;</code>
     */
    public ChatProto.Builder getChatBuilder(
        int index) {
      return getChatFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ChatProto chat = 1;</code>
     */
    public ChatProtoOrBuilder getChatOrBuilder(
        int index) {
      if (chatBuilder_ == null) {
        return chat_.get(index);  } else {
        return chatBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ChatProto chat = 1;</code>
     */
    public java.util.List<? extends ChatProtoOrBuilder>
         getChatOrBuilderList() {
      if (chatBuilder_ != null) {
        return chatBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(chat_);
      }
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ChatProto chat = 1;</code>
     */
    public ChatProto.Builder addChatBuilder() {
      return getChatFieldBuilder().addBuilder(
          ChatProto.getDefaultInstance());
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ChatProto chat = 1;</code>
     */
    public ChatProto.Builder addChatBuilder(
        int index) {
      return getChatFieldBuilder().addBuilder(
          index, ChatProto.getDefaultInstance());
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ChatProto chat = 1;</code>
     */
    public java.util.List<ChatProto.Builder>
         getChatBuilderList() {
      return getChatFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            ChatProto, ChatProto.Builder, ChatProtoOrBuilder>
        getChatFieldBuilder() {
      if (chatBuilder_ == null) {
        chatBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                ChatProto, ChatProto.Builder, ChatProtoOrBuilder>(
                chat_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        chat_ = null;
      }
      return chatBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.tsemkalo.businesscards.generated.ChatProtoList)
  }

  // @@protoc_insertion_point(class_scope:com.tsemkalo.businesscards.generated.ChatProtoList)
  private static final ChatProtoList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ChatProtoList();
  }

  public static ChatProtoList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChatProtoList>
      PARSER = new com.google.protobuf.AbstractParser<ChatProtoList>() {
    public ChatProtoList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatProtoList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ChatProtoList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChatProtoList> getParserForType() {
    return PARSER;
  }

  public ChatProtoList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

