// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CardService.proto

package com.tsemkalo.businesscards.generatedProtos;

public interface DeleteAddressProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tsemkalo.businesscards.generated.DeleteAddressProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 addressId = 1;</code>
   */
  long getAddressId();

  /**
   * <code>int64 currentUserId = 2;</code>
   */
  long getCurrentUserId();

  /**
   * <code>bool admin = 3;</code>
   */
  boolean getAdmin();

  /**
   * <code>int64 cardId = 4;</code>
   */
  long getCardId();
}
