// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CardService.proto

package com.tsemkalo.businesscards.generatedProtos;

/**
 * Protobuf type {@code com.tsemkalo.businesscards.generated.EditCardProto}
 */
public  final class EditCardProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.tsemkalo.businesscards.generated.EditCardProto)
    EditCardProtoOrBuilder {
  // Use EditCardProto.newBuilder() to construct.
  private EditCardProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EditCardProto() {
    currentUserId_ = 0L;
    admin_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private EditCardProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            CardProto.Builder subBuilder = null;
            if (cardProto_ != null) {
              subBuilder = cardProto_.toBuilder();
            }
            cardProto_ = input.readMessage(CardProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(cardProto_);
              cardProto_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            currentUserId_ = input.readInt64();
            break;
          }
          case 24: {

            admin_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CardServiceOuterClass.internal_static_com_tsemkalo_businesscards_EditCardProto_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CardServiceOuterClass.internal_static_com_tsemkalo_businesscards_EditCardProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            EditCardProto.class, EditCardProto.Builder.class);
  }

  public static final int CARDPROTO_FIELD_NUMBER = 1;
  private CardProto cardProto_;
  /**
   * <code>.com.tsemkalo.businesscards.generated.CardProto cardProto = 1;</code>
   */
  public boolean hasCardProto() {
    return cardProto_ != null;
  }
  /**
   * <code>.com.tsemkalo.businesscards.generated.CardProto cardProto = 1;</code>
   */
  public CardProto getCardProto() {
    return cardProto_ == null ? CardProto.getDefaultInstance() : cardProto_;
  }
  /**
   * <code>.com.tsemkalo.businesscards.generated.CardProto cardProto = 1;</code>
   */
  public CardProtoOrBuilder getCardProtoOrBuilder() {
    return getCardProto();
  }

  public static final int CURRENTUSERID_FIELD_NUMBER = 2;
  private long currentUserId_;
  /**
   * <code>int64 currentUserId = 2;</code>
   */
  public long getCurrentUserId() {
    return currentUserId_;
  }

  public static final int ADMIN_FIELD_NUMBER = 3;
  private boolean admin_;
  /**
   * <code>bool admin = 3;</code>
   */
  public boolean getAdmin() {
    return admin_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (cardProto_ != null) {
      output.writeMessage(1, getCardProto());
    }
    if (currentUserId_ != 0L) {
      output.writeInt64(2, currentUserId_);
    }
    if (admin_ != false) {
      output.writeBool(3, admin_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (cardProto_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCardProto());
    }
    if (currentUserId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, currentUserId_);
    }
    if (admin_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, admin_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof EditCardProto)) {
      return super.equals(obj);
    }
    EditCardProto other = (EditCardProto) obj;

    boolean result = true;
    result = result && (hasCardProto() == other.hasCardProto());
    if (hasCardProto()) {
      result = result && getCardProto()
          .equals(other.getCardProto());
    }
    result = result && (getCurrentUserId()
        == other.getCurrentUserId());
    result = result && (getAdmin()
        == other.getAdmin());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCardProto()) {
      hash = (37 * hash) + CARDPROTO_FIELD_NUMBER;
      hash = (53 * hash) + getCardProto().hashCode();
    }
    hash = (37 * hash) + CURRENTUSERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCurrentUserId());
    hash = (37 * hash) + ADMIN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAdmin());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static EditCardProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static EditCardProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static EditCardProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static EditCardProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static EditCardProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static EditCardProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static EditCardProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static EditCardProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static EditCardProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static EditCardProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static EditCardProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static EditCardProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(EditCardProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.tsemkalo.businesscards.generated.EditCardProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.tsemkalo.businesscards.generated.EditCardProto)
          EditCardProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CardServiceOuterClass.internal_static_com_tsemkalo_businesscards_EditCardProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CardServiceOuterClass.internal_static_com_tsemkalo_businesscards_EditCardProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EditCardProto.class, EditCardProto.Builder.class);
    }

    // Construct using com.tsemkalo.businesscards.generated.EditCardProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (cardProtoBuilder_ == null) {
        cardProto_ = null;
      } else {
        cardProto_ = null;
        cardProtoBuilder_ = null;
      }
      currentUserId_ = 0L;

      admin_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CardServiceOuterClass.internal_static_com_tsemkalo_businesscards_EditCardProto_descriptor;
    }

    public EditCardProto getDefaultInstanceForType() {
      return EditCardProto.getDefaultInstance();
    }

    public EditCardProto build() {
      EditCardProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public EditCardProto buildPartial() {
      EditCardProto result = new EditCardProto(this);
      if (cardProtoBuilder_ == null) {
        result.cardProto_ = cardProto_;
      } else {
        result.cardProto_ = cardProtoBuilder_.build();
      }
      result.currentUserId_ = currentUserId_;
      result.admin_ = admin_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof EditCardProto) {
        return mergeFrom((EditCardProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(EditCardProto other) {
      if (other == EditCardProto.getDefaultInstance()) return this;
      if (other.hasCardProto()) {
        mergeCardProto(other.getCardProto());
      }
      if (other.getCurrentUserId() != 0L) {
        setCurrentUserId(other.getCurrentUserId());
      }
      if (other.getAdmin() != false) {
        setAdmin(other.getAdmin());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      EditCardProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (EditCardProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private CardProto cardProto_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
            CardProto, CardProto.Builder, CardProtoOrBuilder> cardProtoBuilder_;
    /**
     * <code>.com.tsemkalo.businesscards.generated.CardProto cardProto = 1;</code>
     */
    public boolean hasCardProto() {
      return cardProtoBuilder_ != null || cardProto_ != null;
    }
    /**
     * <code>.com.tsemkalo.businesscards.generated.CardProto cardProto = 1;</code>
     */
    public CardProto getCardProto() {
      if (cardProtoBuilder_ == null) {
        return cardProto_ == null ? CardProto.getDefaultInstance() : cardProto_;
      } else {
        return cardProtoBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.tsemkalo.businesscards.generated.CardProto cardProto = 1;</code>
     */
    public Builder setCardProto(CardProto value) {
      if (cardProtoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cardProto_ = value;
        onChanged();
      } else {
        cardProtoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.tsemkalo.businesscards.generated.CardProto cardProto = 1;</code>
     */
    public Builder setCardProto(
        CardProto.Builder builderForValue) {
      if (cardProtoBuilder_ == null) {
        cardProto_ = builderForValue.build();
        onChanged();
      } else {
        cardProtoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.tsemkalo.businesscards.generated.CardProto cardProto = 1;</code>
     */
    public Builder mergeCardProto(CardProto value) {
      if (cardProtoBuilder_ == null) {
        if (cardProto_ != null) {
          cardProto_ =
            CardProto.newBuilder(cardProto_).mergeFrom(value).buildPartial();
        } else {
          cardProto_ = value;
        }
        onChanged();
      } else {
        cardProtoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.tsemkalo.businesscards.generated.CardProto cardProto = 1;</code>
     */
    public Builder clearCardProto() {
      if (cardProtoBuilder_ == null) {
        cardProto_ = null;
        onChanged();
      } else {
        cardProto_ = null;
        cardProtoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.tsemkalo.businesscards.generated.CardProto cardProto = 1;</code>
     */
    public CardProto.Builder getCardProtoBuilder() {
      
      onChanged();
      return getCardProtoFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.tsemkalo.businesscards.generated.CardProto cardProto = 1;</code>
     */
    public CardProtoOrBuilder getCardProtoOrBuilder() {
      if (cardProtoBuilder_ != null) {
        return cardProtoBuilder_.getMessageOrBuilder();
      } else {
        return cardProto_ == null ?
            CardProto.getDefaultInstance() : cardProto_;
      }
    }
    /**
     * <code>.com.tsemkalo.businesscards.generated.CardProto cardProto = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            CardProto, CardProto.Builder, CardProtoOrBuilder>
        getCardProtoFieldBuilder() {
      if (cardProtoBuilder_ == null) {
        cardProtoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                CardProto, CardProto.Builder, CardProtoOrBuilder>(
                getCardProto(),
                getParentForChildren(),
                isClean());
        cardProto_ = null;
      }
      return cardProtoBuilder_;
    }

    private long currentUserId_ ;
    /**
     * <code>int64 currentUserId = 2;</code>
     */
    public long getCurrentUserId() {
      return currentUserId_;
    }
    /**
     * <code>int64 currentUserId = 2;</code>
     */
    public Builder setCurrentUserId(long value) {
      
      currentUserId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 currentUserId = 2;</code>
     */
    public Builder clearCurrentUserId() {
      
      currentUserId_ = 0L;
      onChanged();
      return this;
    }

    private boolean admin_ ;
    /**
     * <code>bool admin = 3;</code>
     */
    public boolean getAdmin() {
      return admin_;
    }
    /**
     * <code>bool admin = 3;</code>
     */
    public Builder setAdmin(boolean value) {
      
      admin_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool admin = 3;</code>
     */
    public Builder clearAdmin() {
      
      admin_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.tsemkalo.businesscards.generated.EditCardProto)
  }

  // @@protoc_insertion_point(class_scope:com.tsemkalo.businesscards.generated.EditCardProto)
  private static final EditCardProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new EditCardProto();
  }

  public static EditCardProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EditCardProto>
      PARSER = new com.google.protobuf.AbstractParser<EditCardProto>() {
    public EditCardProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new EditCardProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EditCardProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EditCardProto> getParserForType() {
    return PARSER;
  }

  public EditCardProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

