// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CardService.proto

package com.tsemkalo.businesscards.generatedProtos;

public interface EditAppearanceProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tsemkalo.businesscards.generated.EditAppearanceProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.tsemkalo.businesscards.generated.AppearanceProto appearanceProto = 1;</code>
   */
  boolean hasAppearanceProto();
  /**
   * <code>.com.tsemkalo.businesscards.generated.AppearanceProto appearanceProto = 1;</code>
   */
  AppearanceProto getAppearanceProto();
  /**
   * <code>.com.tsemkalo.businesscards.generated.AppearanceProto appearanceProto = 1;</code>
   */
  AppearanceProtoOrBuilder getAppearanceProtoOrBuilder();

  /**
   * <code>int64 currentUserId = 2;</code>
   */
  long getCurrentUserId();

  /**
   * <code>bool admin = 3;</code>
   */
  boolean getAdmin();

  /**
   * <code>int64 cardId = 4;</code>
   */
  long getCardId();
}
