// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CardService.proto

package com.tsemkalo.businesscards.generatedProtos;

public interface EditAddressProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tsemkalo.businesscards.generated.EditAddressProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.tsemkalo.businesscards.generated.AddressProto addressProto = 1;</code>
   */
  boolean hasAddressProto();
  /**
   * <code>.com.tsemkalo.businesscards.generated.AddressProto addressProto = 1;</code>
   */
  AddressProto getAddressProto();
  /**
   * <code>.com.tsemkalo.businesscards.generated.AddressProto addressProto = 1;</code>
   */
  AddressProtoOrBuilder getAddressProtoOrBuilder();

  /**
   * <code>int64 currentUserId = 2;</code>
   */
  long getCurrentUserId();

  /**
   * <code>bool admin = 3;</code>
   */
  boolean getAdmin();

  /**
   * <code>int64 cardId = 4;</code>
   */
  long getCardId();
}
