// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AdminService.proto

package com.tsemkalo.businesscards.generatedProtos;

/**
 * Protobuf type {@code com.tsemkalo.businesscards.generated.ErrorMessageProtoList}
 */
public  final class ErrorMessageProtoList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.tsemkalo.businesscards.generated.ErrorMessageProtoList)
    ErrorMessageProtoListOrBuilder {
  // Use ErrorMessageProtoList.newBuilder() to construct.
  private ErrorMessageProtoList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ErrorMessageProtoList() {
    errorProtos_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ErrorMessageProtoList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              errorProtos_ = new java.util.ArrayList<ErrorMessageProto>();
              mutable_bitField0_ |= 0x00000001;
            }
            errorProtos_.add(
                input.readMessage(ErrorMessageProto.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        errorProtos_ = java.util.Collections.unmodifiableList(errorProtos_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return AdminServiceOuterClass.internal_static_com_tsemkalo_businesscards_ErrorMessageProtoList_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return AdminServiceOuterClass.internal_static_com_tsemkalo_businesscards_ErrorMessageProtoList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ErrorMessageProtoList.class, ErrorMessageProtoList.Builder.class);
  }

  public static final int ERRORPROTOS_FIELD_NUMBER = 1;
  private java.util.List<ErrorMessageProto> errorProtos_;
  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.ErrorMessageProto errorProtos = 1;</code>
   */
  public java.util.List<ErrorMessageProto> getErrorProtosList() {
    return errorProtos_;
  }
  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.ErrorMessageProto errorProtos = 1;</code>
   */
  public java.util.List<? extends ErrorMessageProtoOrBuilder>
      getErrorProtosOrBuilderList() {
    return errorProtos_;
  }
  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.ErrorMessageProto errorProtos = 1;</code>
   */
  public int getErrorProtosCount() {
    return errorProtos_.size();
  }
  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.ErrorMessageProto errorProtos = 1;</code>
   */
  public ErrorMessageProto getErrorProtos(int index) {
    return errorProtos_.get(index);
  }
  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.ErrorMessageProto errorProtos = 1;</code>
   */
  public ErrorMessageProtoOrBuilder getErrorProtosOrBuilder(
      int index) {
    return errorProtos_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < errorProtos_.size(); i++) {
      output.writeMessage(1, errorProtos_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < errorProtos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, errorProtos_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ErrorMessageProtoList)) {
      return super.equals(obj);
    }
    ErrorMessageProtoList other = (ErrorMessageProtoList) obj;

    boolean result = true;
    result = result && getErrorProtosList()
        .equals(other.getErrorProtosList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getErrorProtosCount() > 0) {
      hash = (37 * hash) + ERRORPROTOS_FIELD_NUMBER;
      hash = (53 * hash) + getErrorProtosList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ErrorMessageProtoList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ErrorMessageProtoList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ErrorMessageProtoList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ErrorMessageProtoList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ErrorMessageProtoList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ErrorMessageProtoList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ErrorMessageProtoList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ErrorMessageProtoList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ErrorMessageProtoList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ErrorMessageProtoList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ErrorMessageProtoList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ErrorMessageProtoList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ErrorMessageProtoList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.tsemkalo.businesscards.generated.ErrorMessageProtoList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.tsemkalo.businesscards.generated.ErrorMessageProtoList)
          ErrorMessageProtoListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AdminServiceOuterClass.internal_static_com_tsemkalo_businesscards_ErrorMessageProtoList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AdminServiceOuterClass.internal_static_com_tsemkalo_businesscards_ErrorMessageProtoList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ErrorMessageProtoList.class, ErrorMessageProtoList.Builder.class);
    }

    // Construct using com.tsemkalo.businesscards.generated.ErrorMessageProtoList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getErrorProtosFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (errorProtosBuilder_ == null) {
        errorProtos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        errorProtosBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return AdminServiceOuterClass.internal_static_com_tsemkalo_businesscards_ErrorMessageProtoList_descriptor;
    }

    public ErrorMessageProtoList getDefaultInstanceForType() {
      return ErrorMessageProtoList.getDefaultInstance();
    }

    public ErrorMessageProtoList build() {
      ErrorMessageProtoList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ErrorMessageProtoList buildPartial() {
      ErrorMessageProtoList result = new ErrorMessageProtoList(this);
      int from_bitField0_ = bitField0_;
      if (errorProtosBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          errorProtos_ = java.util.Collections.unmodifiableList(errorProtos_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.errorProtos_ = errorProtos_;
      } else {
        result.errorProtos_ = errorProtosBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ErrorMessageProtoList) {
        return mergeFrom((ErrorMessageProtoList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ErrorMessageProtoList other) {
      if (other == ErrorMessageProtoList.getDefaultInstance()) return this;
      if (errorProtosBuilder_ == null) {
        if (!other.errorProtos_.isEmpty()) {
          if (errorProtos_.isEmpty()) {
            errorProtos_ = other.errorProtos_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureErrorProtosIsMutable();
            errorProtos_.addAll(other.errorProtos_);
          }
          onChanged();
        }
      } else {
        if (!other.errorProtos_.isEmpty()) {
          if (errorProtosBuilder_.isEmpty()) {
            errorProtosBuilder_.dispose();
            errorProtosBuilder_ = null;
            errorProtos_ = other.errorProtos_;
            bitField0_ = (bitField0_ & ~0x00000001);
            errorProtosBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getErrorProtosFieldBuilder() : null;
          } else {
            errorProtosBuilder_.addAllMessages(other.errorProtos_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ErrorMessageProtoList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ErrorMessageProtoList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<ErrorMessageProto> errorProtos_ =
      java.util.Collections.emptyList();
    private void ensureErrorProtosIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        errorProtos_ = new java.util.ArrayList<ErrorMessageProto>(errorProtos_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            ErrorMessageProto, ErrorMessageProto.Builder, ErrorMessageProtoOrBuilder> errorProtosBuilder_;

    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ErrorMessageProto errorProtos = 1;</code>
     */
    public java.util.List<ErrorMessageProto> getErrorProtosList() {
      if (errorProtosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(errorProtos_);
      } else {
        return errorProtosBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ErrorMessageProto errorProtos = 1;</code>
     */
    public int getErrorProtosCount() {
      if (errorProtosBuilder_ == null) {
        return errorProtos_.size();
      } else {
        return errorProtosBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ErrorMessageProto errorProtos = 1;</code>
     */
    public ErrorMessageProto getErrorProtos(int index) {
      if (errorProtosBuilder_ == null) {
        return errorProtos_.get(index);
      } else {
        return errorProtosBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ErrorMessageProto errorProtos = 1;</code>
     */
    public Builder setErrorProtos(
        int index, ErrorMessageProto value) {
      if (errorProtosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureErrorProtosIsMutable();
        errorProtos_.set(index, value);
        onChanged();
      } else {
        errorProtosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ErrorMessageProto errorProtos = 1;</code>
     */
    public Builder setErrorProtos(
        int index, ErrorMessageProto.Builder builderForValue) {
      if (errorProtosBuilder_ == null) {
        ensureErrorProtosIsMutable();
        errorProtos_.set(index, builderForValue.build());
        onChanged();
      } else {
        errorProtosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ErrorMessageProto errorProtos = 1;</code>
     */
    public Builder addErrorProtos(ErrorMessageProto value) {
      if (errorProtosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureErrorProtosIsMutable();
        errorProtos_.add(value);
        onChanged();
      } else {
        errorProtosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ErrorMessageProto errorProtos = 1;</code>
     */
    public Builder addErrorProtos(
        int index, ErrorMessageProto value) {
      if (errorProtosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureErrorProtosIsMutable();
        errorProtos_.add(index, value);
        onChanged();
      } else {
        errorProtosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ErrorMessageProto errorProtos = 1;</code>
     */
    public Builder addErrorProtos(
        ErrorMessageProto.Builder builderForValue) {
      if (errorProtosBuilder_ == null) {
        ensureErrorProtosIsMutable();
        errorProtos_.add(builderForValue.build());
        onChanged();
      } else {
        errorProtosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ErrorMessageProto errorProtos = 1;</code>
     */
    public Builder addErrorProtos(
        int index, ErrorMessageProto.Builder builderForValue) {
      if (errorProtosBuilder_ == null) {
        ensureErrorProtosIsMutable();
        errorProtos_.add(index, builderForValue.build());
        onChanged();
      } else {
        errorProtosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ErrorMessageProto errorProtos = 1;</code>
     */
    public Builder addAllErrorProtos(
        java.lang.Iterable<? extends ErrorMessageProto> values) {
      if (errorProtosBuilder_ == null) {
        ensureErrorProtosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, errorProtos_);
        onChanged();
      } else {
        errorProtosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ErrorMessageProto errorProtos = 1;</code>
     */
    public Builder clearErrorProtos() {
      if (errorProtosBuilder_ == null) {
        errorProtos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        errorProtosBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ErrorMessageProto errorProtos = 1;</code>
     */
    public Builder removeErrorProtos(int index) {
      if (errorProtosBuilder_ == null) {
        ensureErrorProtosIsMutable();
        errorProtos_.remove(index);
        onChanged();
      } else {
        errorProtosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ErrorMessageProto errorProtos = 1;</code>
     */
    public ErrorMessageProto.Builder getErrorProtosBuilder(
        int index) {
      return getErrorProtosFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ErrorMessageProto errorProtos = 1;</code>
     */
    public ErrorMessageProtoOrBuilder getErrorProtosOrBuilder(
        int index) {
      if (errorProtosBuilder_ == null) {
        return errorProtos_.get(index);  } else {
        return errorProtosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ErrorMessageProto errorProtos = 1;</code>
     */
    public java.util.List<? extends ErrorMessageProtoOrBuilder>
         getErrorProtosOrBuilderList() {
      if (errorProtosBuilder_ != null) {
        return errorProtosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(errorProtos_);
      }
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ErrorMessageProto errorProtos = 1;</code>
     */
    public ErrorMessageProto.Builder addErrorProtosBuilder() {
      return getErrorProtosFieldBuilder().addBuilder(
          ErrorMessageProto.getDefaultInstance());
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ErrorMessageProto errorProtos = 1;</code>
     */
    public ErrorMessageProto.Builder addErrorProtosBuilder(
        int index) {
      return getErrorProtosFieldBuilder().addBuilder(
          index, ErrorMessageProto.getDefaultInstance());
    }
    /**
     * <code>repeated .com.tsemkalo.businesscards.generated.ErrorMessageProto errorProtos = 1;</code>
     */
    public java.util.List<ErrorMessageProto.Builder>
         getErrorProtosBuilderList() {
      return getErrorProtosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            ErrorMessageProto, ErrorMessageProto.Builder, ErrorMessageProtoOrBuilder>
        getErrorProtosFieldBuilder() {
      if (errorProtosBuilder_ == null) {
        errorProtosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                ErrorMessageProto, ErrorMessageProto.Builder, ErrorMessageProtoOrBuilder>(
                errorProtos_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        errorProtos_ = null;
      }
      return errorProtosBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.tsemkalo.businesscards.generated.ErrorMessageProtoList)
  }

  // @@protoc_insertion_point(class_scope:com.tsemkalo.businesscards.generated.ErrorMessageProtoList)
  private static final ErrorMessageProtoList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ErrorMessageProtoList();
  }

  public static ErrorMessageProtoList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ErrorMessageProtoList>
      PARSER = new com.google.protobuf.AbstractParser<ErrorMessageProtoList>() {
    public ErrorMessageProtoList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ErrorMessageProtoList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ErrorMessageProtoList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ErrorMessageProtoList> getParserForType() {
    return PARSER;
  }

  public ErrorMessageProtoList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

