// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AdminService.proto

package com.tsemkalo.businesscards.generatedProtos;

public interface ErrorMessageProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tsemkalo.businesscards.generated.ErrorMessageProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>int32 code = 2;</code>
   */
  int getCode();

  /**
   * <code>string reason = 3;</code>
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 3;</code>
   */
  com.google.protobuf.ByteString
      getReasonBytes();
}
