// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageService.proto

package com.tsemkalo.businesscards.generatedProtos;

public interface InviteMemberRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tsemkalo.businesscards.generated.InviteMemberRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userId = 1;</code>
   */
  long getUserId();

  /**
   * <code>int64 chatId = 2;</code>
   */
  long getChatId();

  /**
   * <code>int64 newMemberId = 3;</code>
   */
  long getNewMemberId();

  /**
   * <code>string newMemberName = 4;</code>
   */
  java.lang.String getNewMemberName();
  /**
   * <code>string newMemberName = 4;</code>
   */
  com.google.protobuf.ByteString
      getNewMemberNameBytes();
}
