// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.tsemkalo.businesscards.generatedProtos;

public interface PermissionProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tsemkalo.businesscards.generated.PermissionProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>.com.tsemkalo.businesscards.generated.ProtoPermissionType name = 2;</code>
   */
  int getNameValue();
  /**
   * <code>.com.tsemkalo.businesscards.generated.ProtoPermissionType name = 2;</code>
   */
  ProtoPermissionType getName();

  /**
   * <code>.com.tsemkalo.businesscards.generated.RoleProto role = 3;</code>
   */
  boolean hasRole();
  /**
   * <code>.com.tsemkalo.businesscards.generated.RoleProto role = 3;</code>
   */
  RoleProto getRole();
  /**
   * <code>.com.tsemkalo.businesscards.generated.RoleProto role = 3;</code>
   */
  RoleProtoOrBuilder getRoleOrBuilder();
}
