// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.tsemkalo.businesscards.generatedProtos;

/**
 * Protobuf type {@code com.tsemkalo.businesscards.generated.PermissionProto}
 */
public  final class PermissionProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.tsemkalo.businesscards.generated.PermissionProto)
    PermissionProtoOrBuilder {
  // Use PermissionProto.newBuilder() to construct.
  private PermissionProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PermissionProto() {
    id_ = 0L;
    name_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private PermissionProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            name_ = rawValue;
            break;
          }
          case 26: {
            RoleProto.Builder subBuilder = null;
            if (role_ != null) {
              subBuilder = role_.toBuilder();
            }
            role_ = input.readMessage(RoleProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(role_);
              role_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return UserServiceOuterClass.internal_static_com_tsemkalo_businesscards_PermissionProto_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return UserServiceOuterClass.internal_static_com_tsemkalo_businesscards_PermissionProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            PermissionProto.class, PermissionProto.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private int name_;
  /**
   * <code>.com.tsemkalo.businesscards.generated.ProtoPermissionType name = 2;</code>
   */
  public int getNameValue() {
    return name_;
  }
  /**
   * <code>.com.tsemkalo.businesscards.generated.ProtoPermissionType name = 2;</code>
   */
  public ProtoPermissionType getName() {
    ProtoPermissionType result = ProtoPermissionType.valueOf(name_);
    return result == null ? ProtoPermissionType.UNRECOGNIZED : result;
  }

  public static final int ROLE_FIELD_NUMBER = 3;
  private RoleProto role_;
  /**
   * <code>.com.tsemkalo.businesscards.generated.RoleProto role = 3;</code>
   */
  public boolean hasRole() {
    return role_ != null;
  }
  /**
   * <code>.com.tsemkalo.businesscards.generated.RoleProto role = 3;</code>
   */
  public RoleProto getRole() {
    return role_ == null ? RoleProto.getDefaultInstance() : role_;
  }
  /**
   * <code>.com.tsemkalo.businesscards.generated.RoleProto role = 3;</code>
   */
  public RoleProtoOrBuilder getRoleOrBuilder() {
    return getRole();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (name_ != ProtoPermissionType.READ.getNumber()) {
      output.writeEnum(2, name_);
    }
    if (role_ != null) {
      output.writeMessage(3, getRole());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (name_ != ProtoPermissionType.READ.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, name_);
    }
    if (role_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getRole());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof PermissionProto)) {
      return super.equals(obj);
    }
    PermissionProto other = (PermissionProto) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && name_ == other.name_;
    result = result && (hasRole() == other.hasRole());
    if (hasRole()) {
      result = result && getRole()
          .equals(other.getRole());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + name_;
    if (hasRole()) {
      hash = (37 * hash) + ROLE_FIELD_NUMBER;
      hash = (53 * hash) + getRole().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static PermissionProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PermissionProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PermissionProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PermissionProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PermissionProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PermissionProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PermissionProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static PermissionProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static PermissionProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static PermissionProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static PermissionProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static PermissionProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(PermissionProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.tsemkalo.businesscards.generated.PermissionProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.tsemkalo.businesscards.generated.PermissionProto)
          PermissionProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserServiceOuterClass.internal_static_com_tsemkalo_businesscards_PermissionProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserServiceOuterClass.internal_static_com_tsemkalo_businesscards_PermissionProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PermissionProto.class, PermissionProto.Builder.class);
    }

    // Construct using com.tsemkalo.businesscards.generated.PermissionProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0L;

      name_ = 0;

      if (roleBuilder_ == null) {
        role_ = null;
      } else {
        role_ = null;
        roleBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return UserServiceOuterClass.internal_static_com_tsemkalo_businesscards_PermissionProto_descriptor;
    }

    public PermissionProto getDefaultInstanceForType() {
      return PermissionProto.getDefaultInstance();
    }

    public PermissionProto build() {
      PermissionProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public PermissionProto buildPartial() {
      PermissionProto result = new PermissionProto(this);
      result.id_ = id_;
      result.name_ = name_;
      if (roleBuilder_ == null) {
        result.role_ = role_;
      } else {
        result.role_ = roleBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof PermissionProto) {
        return mergeFrom((PermissionProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(PermissionProto other) {
      if (other == PermissionProto.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.name_ != 0) {
        setNameValue(other.getNameValue());
      }
      if (other.hasRole()) {
        mergeRole(other.getRole());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      PermissionProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (PermissionProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private int name_ = 0;
    /**
     * <code>.com.tsemkalo.businesscards.generated.ProtoPermissionType name = 2;</code>
     */
    public int getNameValue() {
      return name_;
    }
    /**
     * <code>.com.tsemkalo.businesscards.generated.ProtoPermissionType name = 2;</code>
     */
    public Builder setNameValue(int value) {
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.tsemkalo.businesscards.generated.ProtoPermissionType name = 2;</code>
     */
    public ProtoPermissionType getName() {
      ProtoPermissionType result = ProtoPermissionType.valueOf(name_);
      return result == null ? ProtoPermissionType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.tsemkalo.businesscards.generated.ProtoPermissionType name = 2;</code>
     */
    public Builder setName(ProtoPermissionType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      name_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.tsemkalo.businesscards.generated.ProtoPermissionType name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = 0;
      onChanged();
      return this;
    }

    private RoleProto role_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
            RoleProto, RoleProto.Builder, RoleProtoOrBuilder> roleBuilder_;
    /**
     * <code>.com.tsemkalo.businesscards.generated.RoleProto role = 3;</code>
     */
    public boolean hasRole() {
      return roleBuilder_ != null || role_ != null;
    }
    /**
     * <code>.com.tsemkalo.businesscards.generated.RoleProto role = 3;</code>
     */
    public RoleProto getRole() {
      if (roleBuilder_ == null) {
        return role_ == null ? RoleProto.getDefaultInstance() : role_;
      } else {
        return roleBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.tsemkalo.businesscards.generated.RoleProto role = 3;</code>
     */
    public Builder setRole(RoleProto value) {
      if (roleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        role_ = value;
        onChanged();
      } else {
        roleBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.tsemkalo.businesscards.generated.RoleProto role = 3;</code>
     */
    public Builder setRole(
        RoleProto.Builder builderForValue) {
      if (roleBuilder_ == null) {
        role_ = builderForValue.build();
        onChanged();
      } else {
        roleBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.tsemkalo.businesscards.generated.RoleProto role = 3;</code>
     */
    public Builder mergeRole(RoleProto value) {
      if (roleBuilder_ == null) {
        if (role_ != null) {
          role_ =
            RoleProto.newBuilder(role_).mergeFrom(value).buildPartial();
        } else {
          role_ = value;
        }
        onChanged();
      } else {
        roleBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.tsemkalo.businesscards.generated.RoleProto role = 3;</code>
     */
    public Builder clearRole() {
      if (roleBuilder_ == null) {
        role_ = null;
        onChanged();
      } else {
        role_ = null;
        roleBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.tsemkalo.businesscards.generated.RoleProto role = 3;</code>
     */
    public RoleProto.Builder getRoleBuilder() {
      
      onChanged();
      return getRoleFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.tsemkalo.businesscards.generated.RoleProto role = 3;</code>
     */
    public RoleProtoOrBuilder getRoleOrBuilder() {
      if (roleBuilder_ != null) {
        return roleBuilder_.getMessageOrBuilder();
      } else {
        return role_ == null ?
            RoleProto.getDefaultInstance() : role_;
      }
    }
    /**
     * <code>.com.tsemkalo.businesscards.generated.RoleProto role = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            RoleProto, RoleProto.Builder, RoleProtoOrBuilder>
        getRoleFieldBuilder() {
      if (roleBuilder_ == null) {
        roleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                RoleProto, RoleProto.Builder, RoleProtoOrBuilder>(
                getRole(),
                getParentForChildren(),
                isClean());
        role_ = null;
      }
      return roleBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.tsemkalo.businesscards.generated.PermissionProto)
  }

  // @@protoc_insertion_point(class_scope:com.tsemkalo.businesscards.generated.PermissionProto)
  private static final PermissionProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new PermissionProto();
  }

  public static PermissionProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PermissionProto>
      PARSER = new com.google.protobuf.AbstractParser<PermissionProto>() {
    public PermissionProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new PermissionProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PermissionProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PermissionProto> getParserForType() {
    return PARSER;
  }

  public PermissionProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

