// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.tsemkalo.businesscards.generatedProtos;

/**
 * Protobuf enum {@code com.tsemkalo.businesscards.generated.ProtoPermissionType}
 */
public enum ProtoPermissionType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>READ = 0;</code>
   */
  READ(0),
  /**
   * <code>EDIT = 1;</code>
   */
  EDIT(1),
  /**
   * <code>FOLLOW_LIKE = 2;</code>
   */
  FOLLOW_LIKE(2),
  /**
   * <code>CHAT = 3;</code>
   */
  CHAT(3),
  /**
   * <code>CONTROL_SUPPORT = 4;</code>
   */
  CONTROL_SUPPORT(4),
  /**
   * <code>RESOLVE_QUESTIONS = 5;</code>
   */
  RESOLVE_QUESTIONS(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>READ = 0;</code>
   */
  public static final int READ_VALUE = 0;
  /**
   * <code>EDIT = 1;</code>
   */
  public static final int EDIT_VALUE = 1;
  /**
   * <code>FOLLOW_LIKE = 2;</code>
   */
  public static final int FOLLOW_LIKE_VALUE = 2;
  /**
   * <code>CHAT = 3;</code>
   */
  public static final int CHAT_VALUE = 3;
  /**
   * <code>CONTROL_SUPPORT = 4;</code>
   */
  public static final int CONTROL_SUPPORT_VALUE = 4;
  /**
   * <code>RESOLVE_QUESTIONS = 5;</code>
   */
  public static final int RESOLVE_QUESTIONS_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ProtoPermissionType valueOf(int value) {
    return forNumber(value);
  }

  public static ProtoPermissionType forNumber(int value) {
    switch (value) {
      case 0: return READ;
      case 1: return EDIT;
      case 2: return FOLLOW_LIKE;
      case 3: return CHAT;
      case 4: return CONTROL_SUPPORT;
      case 5: return RESOLVE_QUESTIONS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ProtoPermissionType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ProtoPermissionType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ProtoPermissionType>() {
          public ProtoPermissionType findValueByNumber(int number) {
            return ProtoPermissionType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return UserServiceOuterClass.getDescriptor().getEnumTypes().get(1);
  }

  private static final ProtoPermissionType[] VALUES = values();

  public static ProtoPermissionType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ProtoPermissionType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.tsemkalo.businesscards.generated.ProtoPermissionType)
}

