// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.tsemkalo.businesscards.generatedProtos;

public interface RoleProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tsemkalo.businesscards.generated.RoleProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>.com.tsemkalo.businesscards.generated.ProtoRoleType name = 2;</code>
   */
  int getNameValue();
  /**
   * <code>.com.tsemkalo.businesscards.generated.ProtoRoleType name = 2;</code>
   */
  ProtoRoleType getName();

  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.PermissionProto permission = 3;</code>
   */
  java.util.List<PermissionProto>
      getPermissionList();
  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.PermissionProto permission = 3;</code>
   */
  PermissionProto getPermission(int index);
  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.PermissionProto permission = 3;</code>
   */
  int getPermissionCount();
  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.PermissionProto permission = 3;</code>
   */
  java.util.List<? extends PermissionProtoOrBuilder>
      getPermissionOrBuilderList();
  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.PermissionProto permission = 3;</code>
   */
  PermissionProtoOrBuilder getPermissionOrBuilder(
      int index);
}
