// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.tsemkalo.businesscards.generatedProtos;

public interface SafeUserProtoListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tsemkalo.businesscards.generated.SafeUserProtoList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.SafeUserProto users = 1;</code>
   */
  java.util.List<SafeUserProto>
      getUsersList();
  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.SafeUserProto users = 1;</code>
   */
  SafeUserProto getUsers(int index);
  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.SafeUserProto users = 1;</code>
   */
  int getUsersCount();
  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.SafeUserProto users = 1;</code>
   */
  java.util.List<? extends SafeUserProtoOrBuilder>
      getUsersOrBuilderList();
  /**
   * <code>repeated .com.tsemkalo.businesscards.generated.SafeUserProto users = 1;</code>
   */
  SafeUserProtoOrBuilder getUsersOrBuilder(
      int index);
}
