// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.tsemkalo.businesscards.generatedProtos;

public interface UserIdProtoListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tsemkalo.businesscards.generated.UserIdProtoList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 userIds = 1;</code>
   */
  java.util.List<java.lang.Long> getUserIdsList();
  /**
   * <code>repeated int64 userIds = 1;</code>
   */
  int getUserIdsCount();
  /**
   * <code>repeated int64 userIds = 1;</code>
   */
  long getUserIds(int index);
}
