// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.tsemkalo.businesscards.generatedProtos;

public interface UserProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tsemkalo.businesscards.generated.UserProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string username = 2;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 3;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string name = 4;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 4;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string surname = 5;</code>
   */
  java.lang.String getSurname();
  /**
   * <code>string surname = 5;</code>
   */
  com.google.protobuf.ByteString
      getSurnameBytes();

  /**
   * <code>.com.tsemkalo.businesscards.generated.RoleProto role = 6;</code>
   */
  boolean hasRole();
  /**
   * <code>.com.tsemkalo.businesscards.generated.RoleProto role = 6;</code>
   */
  RoleProto getRole();
  /**
   * <code>.com.tsemkalo.businesscards.generated.RoleProto role = 6;</code>
   */
  RoleProtoOrBuilder getRoleOrBuilder();

  /**
   * <code>string email = 7;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 7;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
